# Generated by Django 3.0.7 on 2020-07-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='选手姓名')),
                ('score', models.FloatField(verbose_name='选手得分')),
            ],
        ),
    ]
