# Generated by Django 3.0.7 on 2020-07-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=20, verbose_name='评委姓名')),
                ('judge_password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='选手姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='评委评分')),
                ('rounds', models.IntegerField(verbose_name='场次')),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Judges')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Player')),
            ],
        ),
    ]
