# Generated by Django 3.0.7 on 2020-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.PositiveIntegerField(verbose_name='选手姓名')),
                ('judge_id', models.PositiveIntegerField(verbose_name='评委id')),
                ('score', models.FloatField(default=0, verbose_name='评委评分')),
                ('rated', models.PositiveIntegerField(default=0, verbose_name='是否评分')),
            ],
            options={
                'verbose_name': '得分',
                'verbose_name_plural': '得分',
            },
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.PositiveIntegerField(verbose_name='评委id')),
                ('judge_name', models.CharField(max_length=20, verbose_name='评委姓名')),
                ('judge_password', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name': '评委',
                'verbose_name_plural': '评委',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.PositiveIntegerField(verbose_name='选手id')),
                ('player_name', models.CharField(max_length=20, verbose_name='选手姓名')),
            ],
            options={
                'verbose_name': '选手',
                'verbose_name_plural': '选手',
            },
        ),
    ]
