# Generated by Django 3.0.7 on 2020-07-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': '得分', 'verbose_name_plural': '得分'},
        ),
        migrations.AlterModelOptions(
            name='judges',
            options={'verbose_name': '评委', 'verbose_name_plural': '评委'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '选手', 'verbose_name_plural': '选手'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='player_name',
        ),
    ]
