# Generated by Django 3.0.7 on 2020-07-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='player_name',
            field=models.CharField(max_length=20, verbose_name='选手姓名'),
        ),
    ]
