# Generated by Django 3.0.7 on 2020-07-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200704_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='rounds',
            field=models.IntegerField(default=0, verbose_name='是否评分'),
        ),
    ]
